/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeliveryLocation {
  'lat' : number,
  'lng' : number,
  'orderId' : bigint,
  'partnerId' : Principal,
  'updatedAt' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'storeId' : bigint,
  'createdAt' : bigint,
  'pinnedLongitude' : number,
  'pinnedLatitude' : number,
  'customerAddress' : string,
  'totalAmount' : [] | [number],
  'itemName' : string,
  'customerId' : Principal,
}
export type OrderStatus = { 'riderAssigned' : null } |
  { 'requested' : null } |
  { 'storeConfirmed' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null };
export interface Product {
  'storeId' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'productId' : bigint,
  'vendorId' : Principal,
  'image' : string,
  'price' : number,
}
export interface ResetLog { 'timestamp' : bigint, 'caller' : Principal }
export interface Store {
  'latitude' : number,
  'storeId' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isOpen' : boolean,
  'deliveryTime' : string,
  'longitude' : number,
  'vendorId' : Principal,
  'category' : string,
  'rating' : number,
  'image' : string,
}
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'store' : null } |
  { 'deliveryP' : null };
export interface _SERVICE {
  'addProduct' : ActorMethod<[bigint, string, string, number, string], bigint>,
  'clearDeliveryLocation' : ActorMethod<[bigint], undefined>,
  'createOrder' : ActorMethod<
    [bigint, string, string, string, string, number, number, number],
    bigint
  >,
  'createStore' : ActorMethod<
    [string, string, string, string, string, number, number],
    bigint
  >,
  'createUserProfile' : ActorMethod<[string, string, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'generateOtp' : ActorMethod<[string], string>,
  'getAllCustomers' : ActorMethod<[], Array<UserProfile>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllStores' : ActorMethod<[], Array<Store>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAllVendors' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getDeliveryLocation' : ActorMethod<[bigint], [] | [DeliveryLocation]>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderStatus' : ActorMethod<[bigint], [] | [OrderStatus]>,
  'getOrdersByCustomer' : ActorMethod<[Principal], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getOrdersByStore' : ActorMethod<[bigint], Array<Order>>,
  'getProductsByVendor' : ActorMethod<[Principal], Array<Product>>,
  'getResetLogs' : ActorMethod<[], Array<ResetLog>>,
  'getStoreById' : ActorMethod<[bigint], [] | [Store]>,
  'getStoreByVendor' : ActorMethod<[Principal], [] | [Store]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendorAnalytics' : ActorMethod<
    [bigint, bigint, bigint],
    {
      'totalOrders' : bigint,
      'totalEarnings' : number,
      'avgOrderValue' : number,
      'todayOrders' : bigint,
    }
  >,
  'getVendorEarningsByDay' : ActorMethod<
    [bigint, bigint, bigint],
    Array<{ 'date' : string, 'earnings' : number }>
  >,
  'getVendorPeakHour' : ActorMethod<
    [bigint, bigint, bigint],
    { 'hourLabel' : string, 'orderCount' : bigint }
  >,
  'getVendorTopProduct' : ActorMethod<
    [bigint, bigint, bigint],
    { 'productName' : string, 'unitsSold' : bigint }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isNewUser' : ActorMethod<[string], boolean>,
  'resetAllData' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleStoreOpen' : ActorMethod<[bigint], boolean>,
  'updateDeliveryLocation' : ActorMethod<[bigint, number, number], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, string],
    undefined
  >,
  'updateStore' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateStoreLocation' : ActorMethod<[bigint, number, number], undefined>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];