/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'store' : IDL.Null,
  'deliveryP' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'riderAssigned' : IDL.Null,
  'requested' : IDL.Null,
  'storeConfirmed' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Int,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'storeId' : IDL.Int,
  'createdAt' : IDL.Int,
  'pinnedLongitude' : IDL.Float64,
  'pinnedLatitude' : IDL.Float64,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Opt(IDL.Float64),
  'itemName' : IDL.Text,
  'customerId' : IDL.Principal,
});
export const Product = IDL.Record({
  'storeId' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'productId' : IDL.Int,
  'vendorId' : IDL.Principal,
  'image' : IDL.Text,
  'price' : IDL.Float64,
});
export const Store = IDL.Record({
  'latitude' : IDL.Float64,
  'storeId' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isOpen' : IDL.Bool,
  'deliveryTime' : IDL.Text,
  'longitude' : IDL.Float64,
  'vendorId' : IDL.Principal,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'image' : IDL.Text,
});
export const DeliveryLocation = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'orderId' : IDL.Int,
  'partnerId' : IDL.Principal,
  'updatedAt' : IDL.Int,
});
export const ResetLog = IDL.Record({
  'timestamp' : IDL.Int,
  'caller' : IDL.Principal,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Int],
      [],
    ),
  'clearDeliveryLocation' : IDL.Func([IDL.Int], [], []),
  'createOrder' : IDL.Func(
      [
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Int],
      [],
    ),
  'createStore' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Int],
      [],
    ),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Int], [], []),
  'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getDeliveryLocation' : IDL.Func(
      [IDL.Int],
      [IDL.Opt(DeliveryLocation)],
      ['query'],
    ),
  'getOrderById' : IDL.Func([IDL.Int], [IDL.Opt(Order)], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Int], [IDL.Opt(OrderStatus)], ['query']),
  'getOrdersByCustomer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getOrdersByStore' : IDL.Func([IDL.Int], [IDL.Vec(Order)], ['query']),
  'getProductsByVendor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getResetLogs' : IDL.Func([], [IDL.Vec(ResetLog)], ['query']),
  'getStoreById' : IDL.Func([IDL.Int], [IDL.Opt(Store)], ['query']),
  'getStoreByVendor' : IDL.Func([IDL.Principal], [IDL.Opt(Store)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendorAnalytics' : IDL.Func(
      [IDL.Int, IDL.Int, IDL.Int],
      [
        IDL.Record({
          'totalOrders' : IDL.Nat,
          'totalEarnings' : IDL.Float64,
          'avgOrderValue' : IDL.Float64,
          'todayOrders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getVendorEarningsByDay' : IDL.Func(
      [IDL.Int, IDL.Int, IDL.Int],
      [IDL.Vec(IDL.Record({ 'date' : IDL.Text, 'earnings' : IDL.Float64 }))],
      ['query'],
    ),
  'getVendorPeakHour' : IDL.Func(
      [IDL.Int, IDL.Int, IDL.Int],
      [IDL.Record({ 'hourLabel' : IDL.Text, 'orderCount' : IDL.Nat })],
      ['query'],
    ),
  'getVendorTopProduct' : IDL.Func(
      [IDL.Int, IDL.Int, IDL.Int],
      [IDL.Record({ 'productName' : IDL.Text, 'unitsSold' : IDL.Nat })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isNewUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'resetAllData' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleStoreOpen' : IDL.Func([IDL.Int], [IDL.Bool], []),
  'updateDeliveryLocation' : IDL.Func(
      [IDL.Int, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Int, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateStore' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateStoreLocation' : IDL.Func([IDL.Int, IDL.Float64, IDL.Float64], [], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'store' : IDL.Null,
    'deliveryP' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'riderAssigned' : IDL.Null,
    'requested' : IDL.Null,
    'storeConfirmed' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Int,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'storeId' : IDL.Int,
    'createdAt' : IDL.Int,
    'pinnedLongitude' : IDL.Float64,
    'pinnedLatitude' : IDL.Float64,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Opt(IDL.Float64),
    'itemName' : IDL.Text,
    'customerId' : IDL.Principal,
  });
  const Product = IDL.Record({
    'storeId' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'productId' : IDL.Int,
    'vendorId' : IDL.Principal,
    'image' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Store = IDL.Record({
    'latitude' : IDL.Float64,
    'storeId' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isOpen' : IDL.Bool,
    'deliveryTime' : IDL.Text,
    'longitude' : IDL.Float64,
    'vendorId' : IDL.Principal,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'image' : IDL.Text,
  });
  const DeliveryLocation = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'orderId' : IDL.Int,
    'partnerId' : IDL.Principal,
    'updatedAt' : IDL.Int,
  });
  const ResetLog = IDL.Record({
    'timestamp' : IDL.Int,
    'caller' : IDL.Principal,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Int],
        [],
      ),
    'clearDeliveryLocation' : IDL.Func([IDL.Int], [], []),
    'createOrder' : IDL.Func(
        [
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Int],
        [],
      ),
    'createStore' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Int],
        [],
      ),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Int], [], []),
    'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllVendors' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getDeliveryLocation' : IDL.Func(
        [IDL.Int],
        [IDL.Opt(DeliveryLocation)],
        ['query'],
      ),
    'getOrderById' : IDL.Func([IDL.Int], [IDL.Opt(Order)], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Int], [IDL.Opt(OrderStatus)], ['query']),
    'getOrdersByCustomer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getOrdersByStore' : IDL.Func([IDL.Int], [IDL.Vec(Order)], ['query']),
    'getProductsByVendor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getResetLogs' : IDL.Func([], [IDL.Vec(ResetLog)], ['query']),
    'getStoreById' : IDL.Func([IDL.Int], [IDL.Opt(Store)], ['query']),
    'getStoreByVendor' : IDL.Func([IDL.Principal], [IDL.Opt(Store)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendorAnalytics' : IDL.Func(
        [IDL.Int, IDL.Int, IDL.Int],
        [
          IDL.Record({
            'totalOrders' : IDL.Nat,
            'totalEarnings' : IDL.Float64,
            'avgOrderValue' : IDL.Float64,
            'todayOrders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getVendorEarningsByDay' : IDL.Func(
        [IDL.Int, IDL.Int, IDL.Int],
        [IDL.Vec(IDL.Record({ 'date' : IDL.Text, 'earnings' : IDL.Float64 }))],
        ['query'],
      ),
    'getVendorPeakHour' : IDL.Func(
        [IDL.Int, IDL.Int, IDL.Int],
        [IDL.Record({ 'hourLabel' : IDL.Text, 'orderCount' : IDL.Nat })],
        ['query'],
      ),
    'getVendorTopProduct' : IDL.Func(
        [IDL.Int, IDL.Int, IDL.Int],
        [IDL.Record({ 'productName' : IDL.Text, 'unitsSold' : IDL.Nat })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isNewUser' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'resetAllData' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleStoreOpen' : IDL.Func([IDL.Int], [IDL.Bool], []),
    'updateDeliveryLocation' : IDL.Func(
        [IDL.Int, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Int, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateStore' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateStoreLocation' : IDL.Func(
        [IDL.Int, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };